version: 2

x-dockerbuild: &dockerbuild
  steps:
    - checkout
    - run: bundle install --with development
    - run: bundle exec rake spec

jobs:
    test-ruby-2.1:
        <<: *dockerbuild
        docker:
          - image: circleci/ruby:2.1-node
    test-ruby-2.2:
        <<: *dockerbuild
        docker:
          - image: circleci/ruby:2.2-node
    test-ruby-2.3:
        <<: *dockerbuild
        docker:
          - image: circleci/ruby:2.3-node
    test-ruby-2.4:
        <<: *dockerbuild
        docker:
          - image: cimg/ruby:2.4-node
    test-ruby-2.5:
        <<: *dockerbuild
        docker:
          - image: cimg/ruby:2.5-node
    test-ruby-2.6:
        <<: *dockerbuild
        docker:
          - image: cimg/ruby:2.6-node
    test-ruby-2.7:
        <<: *dockerbuild
        docker:
          - image: cimg/ruby:2.7-node
    test-ruby-3.0:
        <<: *dockerbuild
        docker:
          - image: cimg/ruby:3.0-node
    test-ruby-3.1:
        <<: *dockerbuild
        docker:
          - image: cimg/ruby:3.1-node
    test-ruby-3.2:
        <<: *dockerbuild
        docker:
          - image: cimg/ruby:3.2-node
    test-ruby-3.3:
        <<: *dockerbuild
        docker:
          - image: cimg/ruby:3.3-node

workflows:
  version: 2
  check_compile:
    jobs:
      - test-ruby-2.1
      - test-ruby-2.2
      - test-ruby-2.3
      - test-ruby-2.4
      - test-ruby-2.5
      - test-ruby-2.6
      - test-ruby-2.7
      - test-ruby-3.0
      - test-ruby-3.1
      - test-ruby-3.2
      - test-ruby-3.3
